# name: GitHub Actions Vercel Preview Deployment
# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#   DATABASE_URL: ${{ secrets.DATABASE_URL }}
# on:
#   push:
#     branches-ignore:
#       - master
# jobs:
#   Deploy-Preview:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - name: Install Vercel CLI
#         run: npm install --global vercel@canary
#       - uses: pnpm/action-setup@v4
#         name: Install pnpm
#         with:
#           run_install: false
#       - name: Install Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 22
#           cache: 'pnpm'
#       - name: Pull Vercel Environment Information
#         run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
#       - name: Build Project Artifacts
#         run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
#       - name: Deploy Project Artifacts to Vercel
#         run: vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
